### PR TITLE
Update for DART 6.7

### PR DESCRIPTION
**Pull request by jslee02**
Use recommended APIs instead of deprecated corresponding.

Note that this PR won't pass the CIs (for Ubuntu >= 14.04) until the issues of gtest and `make_unique()`. I breakdown #479 into smaller ones to make the review process, and this is one of them.

***

**Before creating a pull request**

- [x] Format code with `make format`

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side
- [x] Summarize this change in `CHANGELOG.md`

### CODE REVIEW

**Comment by jslee02** [comment]
Please note that DART 6.7 is not available on Trusty. Let's either drop supporting Trusty for AIKIDO or change this PR to support both of DART 6.6 and DART 6.7.

**Comment by brianhou** [comment]
We'll discuss during lab meeting on Friday, but I'm heavily leaning toward just dropping Trusty support.

**Comment by jslee02** [comment]
Updated to support both of DART 6.6 and DART 6.7 so that we now can merge this regardless of whether to support Trusty or not.

**Comment by jslee02** [comment]
Could someone please run `make format` this PR for me? I don't have available Ubuntu version for this. Thanks!

**Comment by jslee02** [comment]
Never mind! It's done!

**Pull request merged**
