### PR TITLE
DART 6 compatability

### PR DESCRIPTION
**Pull request by mkoval**
This pull request makes the changes to Aikido necessary to link against DART 6, instead of the outdated snapshot we have been developing against.

Before merging this pull request, we need to:

- [x] Investigate why `test_MotionValidator` is failing.
- [x] Investigate why `test_StepSequence` is failing.
- [x] Update `aikido_perception`.
- [x] Update `aikido_rviz`.
- [x] Update `dart_examples`.

---
This change is [Reviewable](https://reviewable.io/reviews/personalrobotics/aikido/104)

### CODE REVIEW

**Comment by jeking04** [comment]
@mkoval I could not recreate the errors in the tests. Here is what I did:

1. Checkout dart ```release-6.0``` branch from the dart repo ```https://github.com/dartsim/dart```
2. Checkout the ```dart6``` branch of aikido
3. Clean my workspace (delete ```devel``` and ```build```)
4. Remove ```ros-indigo-nlopt``` using apt, keeping ```libnlopt-dev``` installed (Otherwise ```dart-optimizer-nlopt``` does not build - I think this might be the currrent problem with the travis build)
5. Build aikido:
```
catkin build aikido
catkin build --make-args tests -- aikido
catkin build --make-args test -- aikido
```

Once I did that all the aikido tests passed. I did this both on my lab machine and on my laptop.

**Comment by mkoval** [comment]
The issue seems to only occur in release mode. Try re-building your workspace after running:
```console
$ catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
```

**Comment by mkoval** [comment]
Also, note that the Travis build on this PR is expected to fail. I need to update the Travis configuration to install DART 6.0 from the Apt repository instead of our custom fork. I am holding off on doing this until this pull request is ready to merge.

**Comment by jeking04** [comment]
Ok. I found the problem. My implementation of the step sequence was returning a bad reference. I fixed it and pushed to this branch. This change also fixed the errors in the ```MotionValidator``` test. @mkoval can you pull and confirm?

**Comment by mkoval** [comment]
Thanks @jeking04! It seems to be fixed. I am good with merging this (and updating Travis accordingly) if there are no objections.

**Comment by mkoval** [comment]
I modified Travis to build DART from the `release-6.0` branch because the DART 6.0.0 `.deb` package is currently broken. Once @jslee02 fixes the package, we can update `pr-rosinstalls` to use the pre-built version and significantly speed up our builds.

I am going ahead and merging this in its current form.

**Pull request merged**
