### PR TITLE
Migrate Aikido to Github Actions

### PR DESCRIPTION
**Pull request by egordon**
Responding to Issue #597 .

This should run the exact same jobs as Travis but on Github Actions instead.

**Before creating a pull request**

- [ N/A ] Document new methods and classes
- [ N/A ] Format code with `make format`

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side
- [x] Summarize this change in `CHANGELOG.md`
- [x] Add unit test(s) for this change

### CODE REVIEW

**Comment by egordon** [comment]
I'm explicitly minimizing the change between these tests and the Travis tests.

However, the AIKIDOPY seems to fail to build because of the WorldInteractiveMarker issue from #521 , but only when building with Catkin... hmm

Should probably investigate that.

**Comment by egordon** [comment]
Will create another PR based on the branch egordon/rviz-world after this is pushed.

**Comment by egordon** [comment]
Issue with Bionic (unclear how we got around this in Travis). Tests are passing, but reporting as failure due to a segfault that happens during cleanup afterwards.

This is due to a mis-match between liboctomap-dev in bionic (version 1.8) and ros-melodic-octomap (version 1.9). I am not sure why catkin seems to get these two version confused.

That said, since both PRL and ICAROS are now updated to focal, we should switch these tests to be focal-centric.

Therefore, this PR now depends on https://github.com/personalrobotics/pr-cleanroom/pull/26

**Comment by egordon** [comment]
Pushed and updated, so ready for review!

**Comment by sniyaz** [comment]
So I've read through and (from what little I understand of GH actions) this seems sane.

One question though- I see we have one test failing currently. Do you know why? I think it's important to fix that before merging.

**Comment by sniyaz** [comment]
> So I've read through and (from what little I understand of GH actions) this seems sane.
> 
> One question though- I see we have one test failing currently. Do you know why? I think it's important to fix that before merging.

Ah, ignore me- I just saw your other PR https://github.com/personalrobotics/aikido/pull/599.

In that case this seems fine- the only feedback is that it would nice to document somewhere how this all works (or even just link to some good documentation from our wiki). I always felt like I had to guess and check with Travis.

That's an issue we've always had, so I don't think it's fair to block this PR on that. Can we make an issue to add this documentation though?

**Review by sniyaz — APPROVED** [review]

**Comment by egordon** [comment]
New wiki page created: https://github.com/personalrobotics/pr_docs/wiki/Continuous-Integration-and-Branch-Setup

**Pull request merged**
