### PR TITLE
OMPL Constrained

### PR DESCRIPTION
**Pull request by jeking04**
This PR contains the following:

1. A port of the ```CRRT``` algorithm from developed by @cdellin in ```pr-constraint```
2. A port of the ```CRRTConnect``` algorithm from that developed by @cdellin in ```pr-constraint```
3. The addition of a ```planConstrained``` function to ```planner::ompl::Planner```
4. The addition of a ```mValid``` flag to OMPL ```GeometricStateSpace::StateType``` that helps indicate when a sample has failed.
5. New tests for all functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/personalrobotics/aikido/100)

### CODE REVIEW

**Comment by psigen** [comment]
Review status: 0 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 74 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6byyF33FGcWkD2JX6:-KH6byyF33FGcWkD2JX7:1938005884) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L74)):*
Is this the right function name?  It's verbose, and I think it's a lab-ism: I don't think it is a common way of expressing that a planning constraint applies globally.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 139 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fT878xJuXXpnc1mr:-KH6fT878xJuXXpnc1ms:-337048372) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L139)):*
nitpick: I think we should be putting closing comments on namespaces like:
```c++
} // namespace planner
} // namespace aikido
```

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 144 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fiWD9gt-TqIAHTkr:-KH6fiWE9sCVMZzA4UPh:-1589845929) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L144)):*
nitpick: I think we should do closing comments on `#endif` like:
```c++
#endif // AIKIDO_PLANNER_OMPL_CRRT_HPP_
```

---

*[aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp, line 37 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fJWOx0fuyfVfL1pR:-KH6fJWOx0fuyfVfL1pS:766319482) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp#L37)):*
I am a little out of the loop.  Can someone briefly explain where this is coming from?

---

*[aikido/tests/planner/ompl/OMPLTestHelpers.hpp, line 43 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6gZJj0y5xhHgy3X2L:-KH6gZJj0y5xhHgy3X2M:-414863321) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/tests/planner/ompl/OMPLTestHelpers.hpp#L43)):*
Does this mean that setting both position limits to 0 will not work for OMPL?

---

*[aikido/tests/planner/ompl/test_CRRT.cpp, line 4 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6gsDiYD5KI7MnIsu-:-KH6gsDiYD5KI7MnIsu0:1651750194) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/tests/planner/ompl/test_CRRT.cpp#L4)):*
Are we filling this in?  If not, let's put in `TODO` comments for later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100)*

**Comment by mkoval** [comment]
One test is failing on Travis:
```
[ RUN      ] GeometricStateSpaceTest.EnforceBoundsProjection
/home/travis/workspace/src/aikido/aikido/tests/planner/ompl/test_GeometricStateSpace.cpp:143: Failure
Value of: getTranslationalState(stateSpace, state) .isApprox(Eigen::Vector3d(-5, 5, 0))
  Actual: false
Expected: true
[  FAILED  ] GeometricStateSpaceTest.EnforceBoundsProjection (1 ms)
```

---

Reviewed 8 of 17 files at r1, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 13 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6ZlOB6jCrKRE3S-kl:-KH6ZlOB6jCrKRE3S-km:-749712174) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L13)):*
Typo: "constraint" -> "constrained"?

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 65 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6_I9RfK03bwZ6Z3jj:-KH6_I9RfK03bwZ6Z3jk:-1097348048) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L65)):*
Typo: "motionto".

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 73 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6_NuSR-1Qos1dmiWS:-KH6_NuSR-1Qos1dmiWT:-1458171046) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L73)):*
A `Projectable` constraint applies to a point, not a trajectory. Can you document how this is transformed into a trajectory-wide constraint? I.e. what resolution is used?

---

*[aikido/include/aikido/planner/ompl/CRRTConnect.hpp, line 53 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6kSbCv8gqmkUqSUa8:-KH6kSbCv8gqmkUqSUa9:-451040322) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRTConnect.hpp#L53)):*
Typo: "motionto"

---

*[aikido/include/aikido/planner/ompl/CRRTConnect.hpp, line 103 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6kc0cd1BsVHy_bjWI:-KH6kc0cd1BsVHy_bjWJ:-2017177913) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRTConnect.hpp#L103)):*
Nit: Prefer `using` aliases to `typedef`s.

---

*[aikido/include/aikido/planner/ompl/CRRTConnect.hpp, line 155 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6o7cwqRNovUEVDzu5:-KH6o7cxoFiI9iJ4pa0K:-289688497) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRTConnect.hpp#L155)):*
Incorrect comment. This is no longer a "PR holonomic" constraint.

---

*[aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp, line 37 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fJWOx0fuyfVfL1pR:-KH6oCcDKYwtsEqS_4e7:845091666) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp#L37)):*
OMPL does not allow a sampler to report failure. We work around this by returning an "invalid state" if sampling fails, then rejecting that state in the state validity checker. This is a slightly less hacky version of setting the entire state to`NaN`s, then checking for that later. @jeking and I have some ideas about how to improve the implementation of this in the future, but this is the most straightforward way of making the planner work.

I believe this independent of constrained planning - this is necessary to make goal sampling work *at all*. @jeking, can you confirm?

---

*[aikido/include/aikido/planner/ompl/Planner.hpp, line 101 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6pzPPm0e_i3ZFUznw:-KH6pzPPm0e_i3ZFUznx:1595660129) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/Planner.hpp#L101)):*
Typo: `_goalSamplers` -> `_goalSampler`.

---

*[aikido/include/aikido/planner/ompl/detail/CRRT-impl.hpp, line 4 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6qGPM2Xq5wDbiWjBH:-KH6qGPM2Xq5wDbiWjBI:-1225231772) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/detail/CRRT-impl.hpp#L4)):*
Missing DART-style `---` separators in this file.

---

*[aikido/src/planner/ompl/CRRT.cpp, line 67 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6rBSR0muQUr-ANEGj:-KH6rBSR0muQUr-ANEGk:-293852350) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRT.cpp#L67)):*
Missing error checking. Shouldn't this be in the range [0, 1].

---

*[aikido/src/planner/ompl/CRRT.cpp, line 78 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6rPsU2B3ipi6xWNo7:-KH6rPsU2B3ipi6xWNo8:-796753865) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRT.cpp#L78)):*
Error checking. Must be positive?

---

*[aikido/src/planner/ompl/CRRT.cpp, line 177 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6ruerEacl7UFkLEBi:-KH6ruerEacl7UFkLEBj:-615939431) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRT.cpp#L177)):*
It looks like this only projects the endpoint. Does that mean `mRange` is the resolution used to enforce the constraint?

This is a bit odd. We would need a *large* number of extensions to reach the goal with a small `mRange` parameter, even if the environment is completely empty. @cdellin and @jeking can you explain the logic behind this?

---

*[aikido/src/planner/ompl/CRRTConnect.cpp, line 138 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6vBNYuZek16bxTgyv:-KH6vBNYuZek16bxTgyw:1472212339) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRTConnect.cpp#L138)):*
Make this magic number a parameter.

---

*[aikido/src/planner/ompl/CRRTConnect.cpp, line 244 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6w5Dp1JKsyZ48NZLp:-KH6w5Dp1JKsyZ48NZLq:-1973203966) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRTConnect.cpp#L244)):*
What is the purpose of this check? Why do we care what fraction of the tree are goal states?

---

*[aikido/src/planner/ompl/CRRTConnect.cpp, line 342 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6wU7duxOKdHMcUDM-:-KH6wU7duxOKdHMcUDM0:872859841) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRTConnect.cpp#L342)):*
We shouldn't print to `cout` in here.

---

*[aikido/tests/planner/ompl/test_CRRT.cpp, line 4 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6gsDiYD5KI7MnIsu-:-KH6x6yGEgGKSpLaq1f1:343174184) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/tests/planner/ompl/test_CRRT.cpp#L4)):*
Aren't we already testing this in OMPLConstrainedTests? @jeking what is the difference between these two files?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-:-KH6xqgb1StqunASNSx0:-1498246087)*

**Comment by psigen** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp, line 37 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fJWOx0fuyfVfL1pR:-KHCGmg0CuuCvkxsd7bO:1880928893) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp#L37)):*
Ok, thanks, that makes sense.  It might be helpful to paste this response into a comment block somewhere in there, it's much more explanatory than the existing comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100)*

**Comment by jeking04** [comment]
Review status: 11 of 21 files reviewed at latest revision, 20 unresolved discussions.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 73 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6_NuSR-1Qos1dmiWS:-KHfQ3YKsCdmIG7g6ke7:-1524926518) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L73)):*
<details><summary><i>Previously, mkoval (Michael Koval) wrote…</i></summary>
> A `Projectable` constraint applies to a point, not a trajectory. Can you document how this is transformed into a trajectory-wide constraint? I.e. what resolution is used?</details>
I struggled with making this comment clear. Check out my update and let me know if you have other ideas.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 74 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6byyF33FGcWkD2JX6:-KHfQdvytJ3Fj0Zmw87U:1037242046) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/CRRT.hpp#L74)):*
<details><summary><i>Previously, psigen (Pras Velagapudi) wrote…</i></summary>
> Is this the right function name?  It's verbose, and I think it's a lab-ism: I don't think it is a common way of expressing that a planning constraint applies globally.</details>
```setPathConstraint```? Thats what ros uses: http://docs.ros.org/jade/api/moveit_msgs/html/definePlanningRequest.html.

---

*[aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp, line 37 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fJWOx0fuyfVfL1pR:-KHfSLRFmmBsPVL2ebiv:1394630896) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp#L37)):*
<details><summary><i>Previously, psigen (Pras Velagapudi) wrote…</i></summary>
> Ok, thanks, that makes sense.  It might be helpful to paste this response into a comment block somewhere in there, it's much more explanatory than the existing comment.</details>
Alrighty, I took a stab at clarifying. Let me know if I made it better or worse.

---

*[aikido/src/planner/ompl/CRRTConnect.cpp, line 244 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6w5Dp1JKsyZ48NZLp:-KHfXkbRPNRCeh4v-L8H:-2117952904) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRTConnect.cpp#L244)):*
<details><summary><i>Previously, mkoval (Michael Koval) wrote…</i></summary>
> What is the purpose of this check? Why do we care what fraction of the tree are goal states?</details>
This is consistent with the vanilla ```RRTConnect``` implementation in OMPL: https://github.com/ompl/ompl/blob/c1bceb665fb09cc55cc7368040fb864a1de729ec/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp#L202

---

*[aikido/tests/planner/ompl/OMPLTestHelpers.hpp, line 43 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6gZJj0y5xhHgy3X2L:-KHfa6nlvdBme61IsyUR:-1325846648) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/tests/planner/ompl/OMPLTestHelpers.hpp#L43)):*
<details><summary><i>Previously, psigen (Pras Velagapudi) wrote…</i></summary>
> Does this mean that setting both position limits to 0 will not work for OMPL?</details>
No, this was just a leftover change from a bugfix. I changed it to back 0 and 0 just to double check that everything still works.

---

*[aikido/tests/planner/ompl/test_CRRT.cpp, line 4 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6gsDiYD5KI7MnIsu-:-KHfYKuB_ZE64ghdyWcs:380066406) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/tests/planner/ompl/test_CRRT.cpp#L4)):*
<details><summary><i>Previously, mkoval (Michael Koval) wrote…</i></summary>
> Aren't we already testing this in OMPLConstrainedTests? @jeking what is the difference between these two files?</details>
```OMPLConstrainedTest``` got left behind when we moved ompl related code under the ```planner``` namespace.  I have now removed it, along with a couple other left behind empty ompl directories.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100)*

**Comment by mkoval** [comment]
Reviewed 4 of 11 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 76 \[r5\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KHhQaDz_sKSltiXUNrd:-KHhQaDz_sKSltiXUNre:1480894490) ([raw file](https://github.com/personalrobotics/aikido/blob/38451f06849fafddb577bfd9e1088cc0767f8549/aikido/include/aikido/planner/ompl/CRRT.hpp#L76)):*
> ```cpp
>   ///  will be at most getRange distance from the node being extend. Therefore,
>   ///  the resolution of the projection is the range set on the planner through
>   ///  setRange.
> ```

I don't think this comment is accurate anymore, since you de-coupled the planner range from the constraint projection resolution.

---

*[aikido/include/aikido/planner/ompl/CRRT.hpp, line 116 \[r5\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KHhQmKX4Kr0Z3Rfq9E0:-KHhQmKX4Kr0Z3Rfq9E1:-1151595819) ([raw file](https://github.com/personalrobotics/aikido/blob/38451f06849fafddb577bfd9e1088cc0767f8549/aikido/include/aikido/planner/ompl/CRRT.hpp#L116)):*
> ```cpp
> 
>     /// Destructor
>     ~Motion(void) {}
> ```

I'd prefer if you moved these implementations to the `.cpp` file.

---

*[aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp, line 37 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fJWOx0fuyfVfL1pR:-KHhR54hOkAw5hXDS-8Z:-1973687782) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp#L37)):*
<details><summary><i>Previously, jeking04 (Jennifer King) wrote…</i></summary>
> Alrighty, I took a stab at clarifying. Let me know if I made it better or worse.</details>
Looks good, but typo: `valide`. Maybe it's the classy version of being valid, like how a "shoppe" is a classy shop? :wink: 

---

*[aikido/src/planner/ompl/CRRT.cpp, line 78 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6rPsU2B3ipi6xWNo7:-KHhRXhUhu19o5zX3Zof:1983575499) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRT.cpp#L78)):*
<details><summary><i>Previously, mkoval (Michael Koval) wrote…</i></summary>
> Error checking. Must be positive?</details>
I think the check should be `<=`, not `<`.

---

*[aikido/src/planner/ompl/CRRTConnect.cpp, line 244 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6w5Dp1JKsyZ48NZLp:-KHhRjA0LhdqgYDb5523:1389201632) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/src/planner/ompl/CRRTConnect.cpp#L244)):*
<details><summary><i>Previously, jeking04 (Jennifer King) wrote…</i></summary>
> This is consistent with the vanilla ```RRTConnect``` implementation in OMPL: https://github.com/ompl/ompl/blob/c1bceb665fb09cc55cc7368040fb864a1de729ec/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp#L202</details>
I'm fine with keeping it for consistency, but I am still confused why the check exists. Do you have any intuition about why it's in the standard `RRTConnect`?

---

*[aikido/tests/planner/ompl/test_OMPLPlanner.cpp, line 152 \[r5\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KHhS7kuCF6urAiRlVme:-KHhS7kuCF6urAiRlVmf:-449277776) ([raw file](https://github.com/personalrobotics/aikido/blob/38451f06849fafddb577bfd9e1088cc0767f8549/aikido/tests/planner/ompl/test_OMPLPlanner.cpp#L152)):*
> ```cpp
> //     EXPECT_TRUE(trajConstraint->isSatisfied(s0));
> //   }
> // }
> ```

Why are all of these tests commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100)*

**Comment by jeking04** [comment]
Review status: 13 of 23 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp, line 37 \[r3\]](https://reviewable.io:443/reviews/personalrobotics/aikido/100#-KH6fJWOx0fuyfVfL1pR:-KHvMai5e_3MCVKFXcox:2100347188) ([raw file](https://github.com/personalrobotics/aikido/blob/8abfffaed4b31aceba0ed4318c66d2020d50c39c/aikido/include/aikido/planner/ompl/GeometricStateSpace.hpp#L37)):*
<details><summary><i>Previously, mkoval (Michael Koval) wrote…</i></summary>
> Looks good, but typo: `valide`. Maybe it's the classy version of being valid, like how a "shoppe" is a classy shop? :wink: 
</details>
I am a classy broad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100)*

**Comment by mkoval** [comment]
Reviewed 1 of 3 files at r6, 3 of 9 files at r7, 6 of 6 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/personalrobotics/aikido/100)*

**Pull request merged**
