### PR TITLE
Vector field planner parameters fix

### PR DESCRIPTION
**Pull request by Tonkel**
Default values for VectorFieldPlannerParameters constructor (as talked about with Gilwoo).

### CODE REVIEW

**Comment by Tonkel** [comment]
this branch is based off of bugfix/IK. Should it merge back to bugfix/IK or master?

**Comment by brianhou** [comment]
I think these parameters can dramatically affect the runtime and success rates of the VectorField planner, so it makes more sense to me to set these in each `librobot`. Why is this change necessary?

**Comment by gilwoolee** [comment]
In the current librobots none of these are set -- just the default constructors are being used, which leads to planning failures or segfaults. We should either explicitly remove the default constructor and force the librobots to set them to some values, or provide some default values. I prefer having a set of good default values that have been benchmarked. @dqyi11 , I asked @Tonkel to copy these values from unit tests; could you verify that these are reasonable parameter values to use?

**Comment by dqyi11** [comment]
Those parameters have not been benchmarked. They were selected for a simple "robot" created in unit tests. Some of the parameters can vary significantly in problems. For example, `linearVelocity` defines how fast we would hope an end-effector moving forward (which usually depends on the movement distance and time). 

Also planning for different functionalities using different vector fields takes different parameters. This one seems for `planToEndEffectorOffset`. Those for `planToEndEffectorPose` would be slightly different. 
If we are going to define default parameters in this way, will it be better to define by functionalities, like `planToTSR`, `planToEndEffectorPose`, etc?

**Comment by gilwoolee** [comment]
Thanks for the comments @dqyi11 ! That makes sense. These were meant originally as a convenient methods until we have planner API, so how about we close this PR and as we work on the planners, set benchmarked planner x problem-specific params? 

@Tonkel Let's keep these only to your local works for ADA for now (you can directly set these params in libada), and revisit after the planner APIs are done.

**Pull request closed without merging**
