### PR TITLE
VanDerCorput Sequence

### PR DESCRIPTION
**Pull request by ClintLiddick**
In-progress PR. Need eyes-on to verify unit test cases and general usage suitability. I intend to wrap this sequence in an iterator API and take the desired terminal resolution as a construction parameter.

---

This change is [Reviewable](https://reviewable.io/reviews/personalrobotics/aikido/37)

### CODE REVIEW

**Comment by mkoval** [comment]
This got lost in the scuffle of merging #32. Could you merge `master` and resolve conflicts?

**Comment by ClintLiddick** [comment]
@jslee02 merged master in #120, so when checks pass this is GTG

**Comment by jslee02** [comment]
I've resolved more conflicts with master.

**Comment by ClintLiddick** [comment]
Done.

**Pull request merged**
