### PR TITLE
Aikido ROS control

### PR DESCRIPTION
**Pull request by ClintLiddick**
@Shushman @mkoval can you compare this with https://github.com/personalrobotics/aikido/pull/103 and see which needs to be worked on? I branched from the `mkoval` branch and made the fix to use the component refactor.

---

This change is [Reviewable](https://reviewable.io/reviews/personalrobotics/aikido/111)

### CODE REVIEW

**Comment by mkoval** [comment]
I would like to split this into several pull requests:

- [ ] `convertJointTrajectory`
- [ ] `RosJointStateClient`
- [ ] `RosTrajectoryExecutor`
- [ ] `ExecutorMultiplexer` and `ExecutorThread` 
- [ ] `printCollisionObject` and `printCollisionResult` #106

This branch is based off of, and supersedes, #103. I am closing that pull request.

**Comment by ClintLiddick** [comment]
This is an ASAP task for me now.

**Comment by ClintLiddick** [comment]
I suck. Ok, I will actually work on verifying and merging this branch now. Especially since personalrobotics/rewd_controllers only works on this branch of aikido.

**Comment by brianhou** [comment]
Closing in favor of various other PRs.

**Pull request closed without merging**
